[NOISSUE] fix(bot): Proxy tag size limit
PluralKit/PluralKit pull request #483
Opened 2022-09-05 01:36 UTC by Oliver-makes-code

Having a proxy tag that's too big causes the bot to throw an error, I went in and created a size limit of 64 for prefix and suffix separately, as that sounded reasonable.

2022-09-05 01:44 UTC, Oliver-makes-code commented
If a different size is needed, then feel free to tell me

2022-09-05 20:09 UTC, spiralw commented
> If a different size is needed, then feel free to tell me

The API has a limit of 100 characters for the entire tag including `text`. I think it's in Limits class, or it should be if it currently isn't

2022-09-20 01:20 UTC, u1f408 requested changes

2022-09-20 01:20 UTC, u1f408 commented on PluralKit.Bot/Commands/MemberProxy.cs
> +            if (prefixAndSuffix[1].length > 64) throw Errors.ProxyTooBig;
Please change this to use the same check (and return the same error) as the proxy tag length check [later in this file (in the "add" subcommand)](https://github.com/PluralKit/PluralKit/blob/528da39e66447e0fc8eab2e993516c12a6585bf6/PluralKit.Bot/Commands/MemberProxy.cs#L70-L72)

2022-09-22 18:08 UTC, spiralw commented
I just noticed this doesn't build, can you fix the build issues? (and preferably test your code before you PR :p)

2022-11-22 09:59 UTC, spiralw commented
fixed in 2745ee61564ef0694d5bae29eea771eaa982d3cd

2022-11-22 09:59 UTC, closed without merging